services:
    db:
        image: "postgres:15"
        restart: unless-stopped
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - db

    app:
        build:
            context: .
        volumes:
            - .:/app
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
                restart: true
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_DATABASE: ${DB_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${NODE_PORT}:${NODE_PORT}"
        networks:
            - db

    loki:
        image: grafana/loki:latest
        user: "root"
        ports:
            - "3100:3100"
        volumes:
            - ./configs/loki.yaml:/etc/loki/loki.yaml
            - ./loki-data:/loki
        command: -config.file=/etc/loki/loki.yaml
        networks:
            - loki

    promtail:
        image: grafana/promtail:latest
        ports:
            - "9080:9080"
        volumes:
            - ./configs/promtail.yaml:/etc/promtail/config.yaml
            - ./src:/var/log
            - ./promtail-data:/tmp
        command: -config.file=/etc/promtail/config.yaml
        networks:
            - loki

    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
        ports:
            - "3000:3000"
        depends_on:
            - loki
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./provisioning:/etc/grafana/provisioning
        networks:
            - loki

volumes:
    db-data:
    grafana-storage:

networks:
    loki:
    db:
