
/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

                            export const postsMinions = {
    "kCreatePostForm": "<h1 id=\"create-post-form-title\">Create New Post</h1>\n\n<form\n    id=\"create-post-form\"\n    hx-post={{createPostUrl}}\n    hx-target=\"#response-message-container\"\n>\n    <label for=\"post-title\">Title:</label>\n    <input type=\"text\" id=\"post-title\" name=\"title\" autocomplete=\"off\" placeholder=\"Enter post title\" required>\n\n    <label for=\"post-description\">Description:</label>\n    <textarea id=\"post-description\" name=\"description\" placeholder=\"Briefly describe your config\" rows=\"15\" required></textarea>\n\n    <button type=\"submit\" class=\"submit-button\">Create Post</button>\n</form>"
};
