import fs from "fs";
import path from "path";
import { convertToCamelCase } from "#shared/utils/index.js";

const dirname = import.meta.dirname;
const modules = fs.readdirSync(path.join(dirname, "../src/modules")).filter((file) => !file.endsWith(".js"));
const sharedMinionsDir = path.join(dirname, "../src/shared/minions");

function generateQueryFile(moduleName, inputDir, outputFile) {
    try {
        const files = fs.readdirSync(inputDir).filter((file) => file.endsWith(".ejs"));

        const minions = {};
        files.forEach((file) => {
            const key = `k${convertToCamelCase(file.slice(0, -4))}`;
            const ejs = fs.readFileSync(path.join(inputDir, file), "utf8").trim();
            minions[key] = ejs;
        });

        const strContent = `\n/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */\n
                            export const ${moduleName}Minions = ${JSON.stringify(minions, null, 4)};\n`;

        fs.writeFileSync(outputFile, strContent, "utf8");
        console.log(`Minions queries generated to: ${outputFile}`);
    } catch (err) {
        console.error("error generating Minions queries:", err);
    }
}

if (fs.existsSync(sharedMinionsDir)) {
    const outputFile = path.join(sharedMinionsDir, "shared-minions.js");
    generateQueryFile("shared", sharedMinionsDir, outputFile);
}

for (let i = 0; i < modules.length; ++i) {
    const inputDir = path.join(dirname, `../src/modules/${modules[i]}/minions`);
    const outputFile = path.join(inputDir, `${modules[i]}-minions.js`);
    generateQueryFile(modules[i], inputDir, outputFile);
}
